# Generated by Django 6.1.1 on 2026-09-07 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(default='#FF4D6D', max_length=20)),
                ('icon_type', models.CharField(blank=True, help_text='e.g. figure, toon, brick, code', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('category_color', models.CharField(default='#FF4D6D', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(max_length=255)),
                ('card_bg', models.CharField(default='#FFEAF0', max_length=20)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('badge_color', models.CharField(default='#FF4D6D', max_length=20)),
                ('rating', models.FloatField(default=5.0)),
                ('reviews', models.IntegerField(default=0)),
                ('price', models.CharField(max_length=50)),
                ('original_price', models.CharField(blank=True, max_length=50, null=True)),
                ('accent', models.CharField(default='#FF4D6D', max_length=20)),
                ('stock', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('eyebrow', models.CharField(max_length=100)),
                ('eyebrow_color', models.CharField(default='#FF4D6D', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('item_count', models.CharField(default='0 items', max_length=50)),
                ('accent', models.CharField(default='#FF4D6D', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_list', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productsection'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=150)),
                ('slug', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.subcategory'),
        ),
    ]
