# Generated by Django 6.1.1 on 2026-09-07 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='edition',
            field=models.CharField(blank=True, default='2,000 worldwide', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_box',
            field=models.TextField(blank=True, default='1/7 scale statue, pre-assembled\nTwo swappable face plates\nLacquered display base'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='PVC + ABS', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='scale',
            field=models.CharField(blank=True, default='1/7 · 28 cm', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='studio',
            field=models.CharField(blank=True, default='Brickverse Studio', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, default='1.4 kg', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='/images/figure-samurai-red.svg', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productsection'),
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='products/gallery/')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
