# Generated by Django 6.1.1 on 2026-09-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_edition_product_image_file_product_in_box_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='product',
            name='badge_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_box',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.CharField(blank=True, default='৳0.00', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='regular_price',
            field=models.CharField(blank=True, default='৳0.00', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='trade_price',
            field=models.CharField(blank=True, default='৳0.00', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default='৳0.00', max_length=50),
        ),
    ]
