# Generated by Django 6.1.1 on 2026-09-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_badge_remove_product_badge_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.CharField(blank=True, default='', help_text='Category icon name, SVG path, or image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='category_icon_file',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icons/'),
        ),
    ]
