# Generated by Django 6.1.1 on 2026-09-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_icon_file',
            field=models.FileField(blank=True, null=True, upload_to='categories/icons/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productgalleryimage',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='products/gallery/'),
        ),
    ]
