# Generated by Django 6.1.1 on 2026-09-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_category_icon_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mega_menu_order',
            field=models.IntegerField(default=0, help_text='Display order within the homepage mega menu'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_mega_menu',
            field=models.BooleanField(default=True, help_text='Show this category in the homepage hero mega menu'),
        ),
    ]
