# Generated by Django 6.1.1 on 2026-09-19 04:54

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_retarget_subcategory_and_drop_subcategory_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.products.models.product_image_upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.products.models.product_image_upload_to),
        ),
        migrations.AlterField(
            model_name='productgalleryimage',
            name='image_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.products.models.product_gallery_upload_to),
        ),
    ]
