# Generated by Django 6.1.1 on 2026-09-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_safe_image_upload_paths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
