# Generated by Django 6.1.1 on 2026-09-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_newest_products_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='homepage_order',
            field=models.IntegerField(default=0, help_text='Display order among the homepage category sections'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Show this top-level category as a product section on the homepage'),
        ),
    ]
