# Generated by Django 6.1.1 on 2026-09-21 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_category_homepage_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('grouped', 'Grouped')], default='simple', max_length=20),
        ),
        migrations.CreateModel(
            name='GroupedProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='used_in_groups', to='products.product')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='products.product')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('group', 'child'), name='unique_child_per_group'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='group_item_quantity_gte_1')],
            },
        ),
    ]
