# Generated by Django 5.2.7 on 2026-10-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_grouped_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this product is active and visible on the website.', verbose_name='Is active'),
        ),
    ]
