# Generated by Django 6.1.1 on 2026-09-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bundle_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
