# Generated by Django 6.1.1 on 2026-09-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_bundle_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_preorder',
            field=models.BooleanField(default=False),
        ),
    ]
