# Generated by Django 5.2.7 on 2026-10-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_is_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, default='Steadfast Courier', max_length=100),
        ),
    ]
