# Generated by Django 6.1.1 on 2026-09-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Free delivery over $60', max_length=200)),
                ('highlight_message', models.CharField(default='Code BUILD10 saves you 10% on your first order', max_length=255)),
                ('coupon_code', models.CharField(blank=True, default='BUILD10', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='✦ New season drop', max_length=100)),
                ('title', models.CharField(default='Build your own universe.', max_length=200)),
                ('highlight_word', models.CharField(default='universe.', max_length=50)),
                ('subtitle', models.TextField(default='Anime figures, cartoon collectibles, brick sets & coding kits — shipped in 48h.')),
                ('primary_btn_text', models.CharField(default='Shop now', max_length=50)),
                ('primary_btn_url', models.CharField(default='#', max_length=200)),
                ('secondary_btn_text', models.CharField(default='Explore sets', max_length=50)),
                ('secondary_btn_url', models.CharField(default='#', max_length=200)),
                ('discount_badge', models.CharField(default='40% OFF TODAY', max_length=50)),
                ('image', models.CharField(default='/images/figure-samurai-red.svg', max_length=255)),
                ('slide_number', models.CharField(default='01 / 03', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Weekend bundle', max_length=100)),
                ('title', models.CharField(default='Buy any two brick sets, get a mini figure free', max_length=200)),
                ('subtitle', models.TextField(default='Mix and match across bricks, robotics and STEM kits. Ends Sunday 11:59pm.')),
                ('button_text', models.CharField(default='Shop bundle', max_length=50)),
                ('button_url', models.CharField(default='#', max_length=200)),
                ('image_left', models.CharField(default='/images/bricks-stack-sunny.svg', max_length=255)),
                ('image_right', models.CharField(default='/images/toon-mascot.svg', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('new_arrivals', 'New Arrivals'), ('deal_of_the_week', 'Deal of the Week'), ('custom', 'Custom')], default='new_arrivals', max_length=50)),
                ('badge_text', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('highlight_word', models.CharField(blank=True, max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(default='Shop now', max_length=50)),
                ('button_url', models.CharField(default='#', max_length=200)),
                ('image', models.CharField(max_length=255)),
                ('has_timer', models.BooleanField(default=False)),
                ('timer_days', models.CharField(blank=True, default='02', max_length=10)),
                ('timer_hours', models.CharField(blank=True, default='14', max_length=10)),
                ('timer_minutes', models.CharField(blank=True, default='36', max_length=10)),
                ('timer_seconds', models.CharField(blank=True, default='09', max_length=10)),
                ('gradient_type', models.CharField(default='purple', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
