# Generated by Django 6.1.1 on 2026-09-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.CharField(default='Free delivery over ৳500', max_length=200),
        ),
    ]
