# Generated by Django 5.2.7 on 2026-10-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_alter_announcement_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.CharField(default='Delivery: ৳60 inside Dhaka · ৳120 nationwide', max_length=200),
        ),
    ]
