# Generated by Django 6.1.1 on 2026-10-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_announcement_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='highlight_message',
            field=models.CharField(default='Fast nationwide delivery across all 64 districts', max_length=255),
        ),
    ]
