# Generated by Django 6.1.1 on 2026-09-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='shipping_address',
        ),
    ]
