# Generated by Django 6.1.1 on 2026-09-07 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(default='#', max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(default='footer_banner', max_length=50)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Brickverse', max_length=100)),
                ('tagline', models.CharField(default='figures · bricks · code kits', max_length=150)),
                ('phone', models.CharField(default='1800 246 010', max_length=50)),
                ('email', models.EmailField(default='hi@brickverse.com.au', max_length=254)),
                ('address', models.TextField(default='14 Maribyrnong St, Footscray VIC 3011')),
                ('about_text', models.TextField(default='Authentic anime figures, cartoon collectibles, brick sets and coding kits. Shipping Australia-wide from our Melbourne warehouse since 2019.')),
                ('facebook_url', models.CharField(blank=True, default='#', max_length=200)),
                ('instagram_url', models.CharField(blank=True, default='#', max_length=200)),
                ('linkedin_url', models.CharField(blank=True, default='#', max_length=200)),
                ('youtube_url', models.CharField(blank=True, default='#', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(default='#', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='marketing.footercolumn')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
