# Generated by Django 6.1.1 on 2026-09-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_heroslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='about_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='name',
            field=models.CharField(default='Kawaii Subete', max_length=100),
        ),
    ]
