# Generated by Django 6.1.1 on 2026-10-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('category', 'Category Banner'), ('offer', 'Offer / Deal Banner')], default='category', max_length=20)),
                ('badge_text', models.CharField(default='New arrivals', help_text="Category badge or Deal type like 'Deal of the week', 'New arrivals'", max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('highlight_word', models.CharField(blank=True, default='', help_text='Word in title to accent/highlight', max_length=100)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('button_text', models.CharField(blank=True, default='Shop now', max_length=50)),
                ('button_url', models.CharField(blank=True, default='/shop', max_length=300)),
                ('image', models.FileField(blank=True, null=True, upload_to='promo_banners/')),
                ('gradient_type', models.CharField(choices=[('purple', 'Purple Gradient (Anime / Figures)'), ('yellow', 'Yellow Gradient (Deals / Bricks)'), ('pink', 'Pink Gradient (Kawaii / Cute)'), ('blue', 'Blue Gradient (Tech / Kits)'), ('dark', 'Dark Night Gradient')], default='purple', max_length=30)),
                ('countdown_end', models.DateTimeField(blank=True, help_text='Expiry date and time for Deal / Offer countdown timer', null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
