# Generated by Django on 2026-10-05

from django.db import migrations
from django.utils import timezone
import datetime


def seed_promo_banners(apps, schema_editor):
    PromoBanner = apps.get_model('marketing', 'PromoBanner')

    # Update or create Banner 1
    b1 = PromoBanner.objects.filter(banner_type='category').order_by('order', 'id').first()
    if b1:
        b1.badge_text = 'New arrivals'
        b1.title = 'Anime figure collection'
        b1.highlight_word = 'collection'
        b1.subtitle = 'Limited runs · Handcrafted collectibles'
        b1.button_text = 'Shop now'
        b1.button_url = '/shop'
        b1.gradient_type = 'purple'
        b1.order = 0
        b1.is_active = True
        b1.save()
    else:
        PromoBanner.objects.create(
            banner_type='category',
            badge_text='New arrivals',
            title='Anime figure collection',
            highlight_word='collection',
            subtitle='Limited runs · Handcrafted collectibles',
            button_text='Shop now',
            button_url='/shop',
            gradient_type='purple',
            order=0,
            is_active=True
        )

    # Update or create Banner 2 with fixed clean English
    b2 = PromoBanner.objects.filter(banner_type='offer').order_by('order', 'id').first()
    if b2:
        b2.badge_text = 'Deal of the week'
        b2.title = 'Use code "LAUNCH10" for 10% off'
        b2.highlight_word = '10% off'
        b2.subtitle = 'Special limited-time discount on all items'
        b2.button_text = 'Grab deal'
        b2.button_url = '/shop?deals=true'
        b2.gradient_type = 'yellow'
        b2.countdown_end = timezone.now() + datetime.timedelta(days=7, hours=12, minutes=30)
        b2.order = 1
        b2.is_active = True
        b2.save()
    else:
        PromoBanner.objects.create(
            banner_type='offer',
            badge_text='Deal of the week',
            title='Use code "LAUNCH10" for 10% off',
            highlight_word='10% off',
            subtitle = 'Special limited-time discount on all items',
            button_text='Grab deal',
            button_url='/shop?deals=true',
            gradient_type='yellow',
            countdown_end=timezone.now() + datetime.timedelta(days=7, hours=12, minutes=30),
            order=1,
            is_active=True
        )


def reverse_seed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_promobanner'),
    ]

    operations = [
        migrations.RunPython(seed_promo_banners, reverse_seed),
    ]
