# Generated by Django 6.1.1 on 2026-09-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('REQUEST', 'Request')], db_index=True, default='INFO', max_length=20)),
                ('source', models.CharField(default='django.request', max_length=120)),
                ('method', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('path', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('status_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
