# Generated by Django 6.1.1 on 2026-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRetentionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.IntegerField(default=1)),
                ('is_auto_delete_enabled', models.BooleanField(default=True)),
                ('last_cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log Retention Setting',
                'verbose_name_plural': 'Log Retention Settings',
            },
        ),
    ]
